<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

namespace Catalog;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>catalog.Book</code>
 */
class Book extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <code>float price = 3;</code>
     */
    private $price = 0.0;

    public function __construct() {
        \GPBMetadata\Book::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>float price = 3;</code>
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * <code>float price = 3;</code>
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;
    }

}

