<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

namespace Catalog;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>catalog.Catalog_Item</code>
 */
class Catalog_Item extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .catalog.Book book = 1;</code>
     */
    private $book;
    /**
     * <code>int32 quant = 2;</code>
     */
    private $quant = 0;

    public function __construct() {
        \GPBMetadata\Book::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .catalog.Book book = 1;</code>
     */
    public function getBook()
    {
        return $this->book;
    }

    /**
     * <code>repeated .catalog.Book book = 1;</code>
     */
    public function setBook(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Catalog\Book::class);
        $this->book = $var;
    }

    /**
     * <code>int32 quant = 2;</code>
     */
    public function getQuant()
    {
        return $this->quant;
    }

    /**
     * <code>int32 quant = 2;</code>
     */
    public function setQuant($var)
    {
        GPBUtil::checkInt32($var);
        $this->quant = $var;
    }

}

