<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Messages.AreYouAlive</code>
 */
class AreYouAlive extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Messages.RequestType type = 1;</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Messages::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.Messages.RequestType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.Messages.RequestType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Messages\RequestType::class);
        $this->type = $var;

        return $this;
    }

}

