<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

require_once __DIR__ . "/../Debug.php";

/**
 * Generated from protobuf message <code>Messages.CatalogItem</code>
 */
class CatalogItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>.Messages.Book book = 2;</code>
     */
    private $book = null;
    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     */
    private $count = 0;

    public function __construct() {
        \GPBMetadata\Messages::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Messages.Book book = 2;</code>
     * @return \Messages\Book
     */
    public function getBook()
    {
        return $this->book;
    }

    /**
     * Generated from protobuf field <code>.Messages.Book book = 2;</code>
     * @param \Messages\Book $var
     * @return $this
     */
    public function setBook($var)
    {
        GPBUtil::checkMessage($var, \Messages\Book::class);
        $this->book = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    public function debug()
    {
        debug_catalog_item($this);
    }
}

