<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Messages.Catalogs</code>
 */
class Catalogs extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Messages.Catalog catalogs = 1;</code>
     */
    private $catalogs;

    public function __construct() {
        \GPBMetadata\Messages::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .Messages.Catalog catalogs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCatalogs()
    {
        return $this->catalogs;
    }

    /**
     * Generated from protobuf field <code>repeated .Messages.Catalog catalogs = 1;</code>
     * @param \Messages\Catalog[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCatalogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Catalog::class);
        $this->catalogs = $arr;

        return $this;
    }

}

