<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto


namespace Messages;

require_once __DIR__ . "/../GPBMetadata/Messages.php";

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
/**
 * Generated from protobuf message <code>Messages.Choice</code>
 */
class Choice extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id_message = 1;</code>
     */
    private $id_message = 0;
    /**
     * Generated from protobuf field <code>int32 id_search = 2;</code>
     */
    private $id_search = 0;
    /**
     * Generated from protobuf field <code>string name_search = 3;</code>
     */
    private $name_search = '';
    /**
     * Generated from protobuf field <code>float place_holder = 4;</code>
     */
    private $place_holder = 0.0;

    public function __construct() {
        \GPBMetadata\Messages::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id_message = 1;</code>
     * @return int
     */
    public function getIdMessage()
    {
        return $this->id_message;
    }

    /**
     * Generated from protobuf field <code>int32 id_message = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIdMessage($var)
    {
        GPBUtil::checkInt32($var);
        $this->id_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 id_search = 2;</code>
     * @return int
     */
    public function getIdSearch()
    {
        return $this->id_search;
    }

    /**
     * Generated from protobuf field <code>int32 id_search = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIdSearch($var)
    {
        GPBUtil::checkInt32($var);
        $this->id_search = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name_search = 3;</code>
     * @return string
     */
    public function getNameSearch()
    {
        return $this->name_search;
    }

    /**
     * Generated from protobuf field <code>string name_search = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNameSearch($var)
    {
        GPBUtil::checkString($var, True);
        $this->name_search = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float place_holder = 4;</code>
     * @return float
     */
    public function getPlaceHolder()
    {
        return $this->place_holder;
    }

    /**
     * Generated from protobuf field <code>float place_holder = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPlaceHolder($var)
    {
        GPBUtil::checkFloat($var);
        $this->place_holder = $var;

        return $this;
    }

}

