<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace Messages;

/**
 * Protobuf enum <code>Messages\RequestType</code>
 */
class RequestType
{
    /**
     * Generated from protobuf enum <code>SEARCH_FOR_CATALOGS = 0;</code>
     */
    const SEARCH_FOR_CATALOGS = 0;
    /**
     * Generated from protobuf enum <code>FIND_CATALOG = 1;</code>
     */
    const FIND_CATALOG = 1;
    /**
     * Generated from protobuf enum <code>UPDATE_CATALOG_PRICE = 2;</code>
     */
    const UPDATE_CATALOG_PRICE = 2;
    /**
     * Generated from protobuf enum <code>UPDATE_CATALOG_COUNT = 3;</code>
     */
    const UPDATE_CATALOG_COUNT = 3;
    /**
     * Generated from protobuf enum <code>BUY_BOOK = 4;</code>
     */
    const BUY_BOOK = 4;
    /**
     * Generated from protobuf enum <code>GET_CATALOG = 5;</code>
     */
    const GET_CATALOG = 5;
}

