<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace Messages;

/**
 * Protobuf enum <code>Messages\RequestType</code>
 */
class RequestType
{
    /**
     * Generated from protobuf enum <code>SEARCH_FOR_CATALOGS = 0;</code>
     */
    const SEARCH_FOR_CATALOGS = 0;
    /**
     * Generated from protobuf enum <code>FIND_CATALOG = 1;</code>
     */
    const FIND_CATALOG = 1;
    /**
     * Generated from protobuf enum <code>UPDATE_CATALOG_PRICE = 2;</code>
     */
    const UPDATE_CATALOG_PRICE = 2;
    /**
     * Generated from protobuf enum <code>UPDATE_CATALOG_COUNT = 3;</code>
     */
    const UPDATE_CATALOG_COUNT = 3;
    /**
     * Generated from protobuf enum <code>BUY_BOOK = 4;</code>
     */
    const BUY_BOOK = 4;
    /**
     * Generated from protobuf enum <code>GET_CATALOG = 5;</code>
     */
    const GET_CATALOG = 5;
    /**
     * Generated from protobuf enum <code>ELECTION = 100;</code>
     */
    const ELECTION = 100;
    /**
     * Generated from protobuf enum <code>ARE_YOU_ALIVE = 101;</code>
     */
    const ARE_YOU_ALIVE = 101;
    /**
     * Generated from protobuf enum <code>I_AM_ALIVE = 102;</code>
     */
    const I_AM_ALIVE = 102;
    /**
     * Generated from protobuf enum <code>UPDATE_COORDINATOR = 103;</code>
     */
    const UPDATE_COORDINATOR = 103;
}

