<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Messages.RequestById</code>
 */
class RequestById extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Messages.RequestType requestType = 1;</code>
     */
    private $requestType = 0;
    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     */
    private $id = 0;

    public function __construct() {
        \GPBMetadata\Messages::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.Messages.RequestType requestType = 1;</code>
     * @return int
     */
    public function getRequestType()
    {
        return $this->requestType;
    }

    /**
     * Generated from protobuf field <code>.Messages.RequestType requestType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestType($var)
    {
        GPBUtil::checkEnum($var, \Messages\RequestType::class);
        $this->requestType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

}

